name: 'Linux tests for PTI'
description: |
  Run the tests with a partition that is expected to ALWAYS succeed and
  another partition that MAY fail. The latter is designated as Quarantine.
inputs:
  wdir:
    description: Working directory
    required: true
  preset:
    description: Preset used in the build to be tested.
    required: true
  skip_hw_metrics:
    description: Skip hw-metrics tests
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:

    - name: Tests that MUST succeed.
      working-directory: ${{ inputs.wdir }}
      shell: bash
      run: |
        source /opt/intel/oneapi/setvars.sh

        EXCLUDE_PATTERN='performance|quarantine'
        if [[ "${{ inputs.skip_hw_metrics }}" == "true" ]]; then
          EXCLUDE_PATTERN="${EXCLUDE_PATTERN}|hw-metrics"
        fi

        ctest --output-on-failure --preset ${{ inputs.preset }} -LE "$EXCLUDE_PATTERN"

    - name: Quarantined tests # performance and flaky tests
      continue-on-error: true
      working-directory: ${{ inputs.wdir }}
      shell: bash
      run: |
        source /opt/intel/oneapi/setvars.sh

        if ctest --output-on-failure --preset ${{ inputs.preset }} -L 'performance|quarantine'; then
          echo "Test status: 0"
          echo "Quarantined tests pass"
        else
          echo "Test status: 1"
          echo "::warning::Quarantined tests failed"
        fi
