name: 'Linux tests for PTI'
description: |
  Run the tests with a partition that is expected to ALWAYS succeed and
  another partition that MAY fail. The latter is designated as Quarantine.
inputs:
  wdir:
    description: Working directory
    required: true
  preset:
    description: Preset used in the build to be tested.
    required: true
  adjust-test-2025-3:
    description: "Skip validate-sycl-ur-api-ids-test"
    default: false
  adjust-test-bmg:
    description: "Exclude known failing test for bmg and oneAPI-2025.3"
    default: false
    type: boolean

runs:
  using: "composite"
  steps:

    - name: Tests that MUST succeed.
      working-directory: ${{ inputs.wdir }}
      shell: bash
      run: |
        source /opt/intel/oneapi/setvars.sh

        #
        # PTI-297.
        # This test is NOT CRITICAL.
        # Tests for bmg+2025.3 are partitioned to have them pass. Notice
        # that a number of them require SYCL_UR_USE_LEVEL_ZERO_V2=0
        # which is a workaround until we resolve PTI-297
        #
        if [[ "${{ inputs.adjust-test-2025-3 }}" == "true" && "${{ inputs.adjust-test-bmg }}" == "true" ]]; then
          echo "BMG+2025.3 test that need SYCL_UR_USE_LEVEL_ZERO_V2-0"
          SYCL_UR_USE_LEVEL_ZERO_V2=0 ctest --preset linux-oneAPI-release -R "RuntimeOpsUnsetMainFixtureTest.NumberOfExpectedMemoryRecordsAfterStopTracing|RuntimeOpsUnsetMainFixtureTest.NumberOfExpectedKernelRecordsAfterStopTracing|RuntimeOpsSetOffMainFixtureTest.NumberOfExpectedMemoryRecordsAfterStopTracing|RuntimeOpsSetOffMainFixtureTest.NumberOfExpectedKernelRecordsAfterStopTracing|RuntimeOpsSetOnMainFixtureTest.NumberOfExpectedMemoryRecordsAfter|NoKernelOverlapAndGapInSubmittingTests"

          echo "BMG+2025.3 test that should pass"
          #
          # Added the temporary skip of MultiThreadedSubmissionFixtureTest
          #
          ctest --preset linux-oneAPI-release -E "RuntimeOpsUnsetMainFixtureTest.NumberOfExpectedMemoryRecordsAfterStopTracing|RuntimeOpsUnsetMainFixtureTest.NumberOfExpectedKernelRecordsAfterStopTracing|RuntimeOpsSetOffMainFixtureTest.NumberOfExpectedMemoryRecordsAfterStopTracing|RuntimeOpsSetOffMainFixtureTest.NumberOfExpectedKernelRecordsAfterStopTracing|RuntimeOpsSetOnMainFixtureTest.NumberOfExpectedMemoryRecordsAfterStopTracing|RuntimeOpsSetOnMainFixtureTest.NumberOfExpectedKernelRecordsAfterStopTracing|NoKernelOverlapAndGapInSubmittingTests|mt-awk-test|perf*"

        else
          ctest --output-on-failure --preset ${{ inputs.preset }} -LE performance 
        fi

    - name: Quarantined tests # flaky tests
      continue-on-error: true
      working-directory: ${{ inputs.wdir }}
      shell: bash
      run: |
        source /opt/intel/oneapi/setvars.sh

        if ctest --output-on-failure --preset ${{ inputs.preset }} -L performance; then
          echo "Test status: 0"
          echo "Quarantine tests all pass."
        else
          echo "Test status: 1"
          echo "::warning::Quarantine tests presented failures."
        fi
        exit 0
