//==============================================================
// Copyright (C) Intel Corporation
//
// SPDX-License-Identifier: MIT
// =============================================================

#include "pti/pti.h"

#include "pti/pti_callback.h"

#define PTI_CASE_ENUM_TO_STRING(e) \
  case e:                          \
    return #e;

const char* ptiResultTypeToString(pti_result result_value) {
  switch (result_value) {
    PTI_CASE_ENUM_TO_STRING(PTI_ERROR_BAD_API_ID)
    PTI_CASE_ENUM_TO_STRING(PTI_ERROR_BAD_ARGUMENT)
    PTI_CASE_ENUM_TO_STRING(PTI_ERROR_BAD_TIMESTAMP)
    PTI_CASE_ENUM_TO_STRING(PTI_ERROR_DRIVER)
    PTI_CASE_ENUM_TO_STRING(PTI_ERROR_EXTERNAL_ID_QUEUE_EMPTY)
    PTI_CASE_ENUM_TO_STRING(PTI_ERROR_INTERNAL)
    PTI_CASE_ENUM_TO_STRING(PTI_ERROR_L0_LOCAL_PROFILING_NOT_SUPPORTED)
    PTI_CASE_ENUM_TO_STRING(PTI_ERROR_METRICS_BAD_COLLECTION_CONFIGURATION)
    PTI_CASE_ENUM_TO_STRING(PTI_ERROR_METRICS_COLLECTION_ALREADY_ENABLED)
    PTI_CASE_ENUM_TO_STRING(PTI_ERROR_METRICS_COLLECTION_ALREADY_PAUSED)
    PTI_CASE_ENUM_TO_STRING(PTI_ERROR_METRICS_COLLECTION_NOT_DISABLED)
    PTI_CASE_ENUM_TO_STRING(PTI_ERROR_METRICS_COLLECTION_NOT_ENABLED)
    PTI_CASE_ENUM_TO_STRING(PTI_ERROR_METRICS_COLLECTION_NOT_PAUSED)
    PTI_CASE_ENUM_TO_STRING(PTI_ERROR_METRICS_NO_DATA_COLLECTED)
    PTI_CASE_ENUM_TO_STRING(PTI_ERROR_METRICS_SCOPE_METRIC_NOT_FOUND)
    PTI_CASE_ENUM_TO_STRING(PTI_ERROR_METRICS_SCOPE_NOT_A_SINGLE_GROUP)
    PTI_CASE_ENUM_TO_STRING(PTI_ERROR_METRICS_SCOPE_OUT_OF_MEMORY)
    PTI_CASE_ENUM_TO_STRING(PTI_ERROR_METRICS_SCOPE_COLLECTION_BUFFER_TOO_SMALL)
    PTI_CASE_ENUM_TO_STRING(PTI_ERROR_METRICS_SCOPE_INSUFFICIENT_BUFFER)
    PTI_CASE_ENUM_TO_STRING(PTI_ERROR_METRICS_SCOPE_INVALID_COLLECTION_BUFFER)
    PTI_CASE_ENUM_TO_STRING(PTI_WARN_METRICS_SCOPE_PARTIAL_BUFFER)
    PTI_CASE_ENUM_TO_STRING(PTI_ERROR_NO_CALLBACKS_SET)
    PTI_CASE_ENUM_TO_STRING(PTI_ERROR_NO_GPU_VIEWS_ENABLED)
    PTI_CASE_ENUM_TO_STRING(PTI_ERROR_NOT_IMPLEMENTED)
    PTI_CASE_ENUM_TO_STRING(PTI_ERROR_TRACING_NOT_INITIALIZED)
    PTI_CASE_ENUM_TO_STRING(PTI_STATUS_END_OF_BUFFER)
    PTI_CASE_ENUM_TO_STRING(PTI_SUCCESS)
  }

  return "INVALID";
}

#undef PTI_CASE_ENUM_TO_STRING
