//==============================================================
// Copyright (C) Intel Corporation
//
// SPDX-License-Identifier: MIT
// =============================================================

#include "pti/pti.h"

#include "pti/pti_callback.h"

#define PTI_CASE_ENUM_TO_STRING(e) \
  case e:                          \
    return #e;

const char* ptiResultTypeToString(pti_result result_value) {
  switch (result_value) {
    PTI_CASE_ENUM_TO_STRING(PTI_ERROR_BAD_API_ID)
    PTI_CASE_ENUM_TO_STRING(PTI_ERROR_BAD_ARGUMENT)
    PTI_CASE_ENUM_TO_STRING(PTI_ERROR_BAD_TIMESTAMP)
    PTI_CASE_ENUM_TO_STRING(PTI_ERROR_DRIVER)
    PTI_CASE_ENUM_TO_STRING(PTI_ERROR_EXTERNAL_ID_QUEUE_EMPTY)
    PTI_CASE_ENUM_TO_STRING(PTI_ERROR_INTERNAL)
    PTI_CASE_ENUM_TO_STRING(PTI_ERROR_L0_LOCAL_PROFILING_NOT_SUPPORTED)
    PTI_CASE_ENUM_TO_STRING(PTI_ERROR_METRICS_BAD_COLLECTION_CONFIGURATION)
    PTI_CASE_ENUM_TO_STRING(PTI_ERROR_METRICS_COLLECTION_ALREADY_ENABLED)
    PTI_CASE_ENUM_TO_STRING(PTI_ERROR_METRICS_COLLECTION_ALREADY_PAUSED)
    PTI_CASE_ENUM_TO_STRING(PTI_ERROR_METRICS_COLLECTION_NOT_DISABLED)
    PTI_CASE_ENUM_TO_STRING(PTI_ERROR_METRICS_COLLECTION_NOT_ENABLED)
    PTI_CASE_ENUM_TO_STRING(PTI_ERROR_METRICS_COLLECTION_NOT_PAUSED)
    PTI_CASE_ENUM_TO_STRING(PTI_ERROR_METRICS_NO_DATA_COLLECTED)
    PTI_CASE_ENUM_TO_STRING(PTI_ERROR_NO_CALLBACKS_SET)
    PTI_CASE_ENUM_TO_STRING(PTI_ERROR_NO_GPU_VIEWS_ENABLED)
    PTI_CASE_ENUM_TO_STRING(PTI_ERROR_NOT_IMPLEMENTED)
    PTI_CASE_ENUM_TO_STRING(PTI_ERROR_TRACING_NOT_INITIALIZED)
    PTI_CASE_ENUM_TO_STRING(PTI_STATUS_END_OF_BUFFER)
    PTI_CASE_ENUM_TO_STRING(PTI_SUCCESS)
  }

  return "INVALID";
}

const char* ptiCallbackDomainTypeToString(pti_callback_domain domain) {
  switch (domain) {
    PTI_CASE_ENUM_TO_STRING(PTI_CB_DOMAIN_DRIVER_API)
    PTI_CASE_ENUM_TO_STRING(PTI_CB_DOMAIN_DRIVER_CONTEXT_CREATED)
    PTI_CASE_ENUM_TO_STRING(PTI_CB_DOMAIN_DRIVER_GPU_OPERATION_APPENDED)
    PTI_CASE_ENUM_TO_STRING(PTI_CB_DOMAIN_DRIVER_GPU_OPERATION_COMPLETED)
    PTI_CASE_ENUM_TO_STRING(PTI_CB_DOMAIN_DRIVER_GPU_OPERATION_DISPATCHED)
    PTI_CASE_ENUM_TO_STRING(PTI_CB_DOMAIN_DRIVER_HOST_SYNCHRONIZATION)
    PTI_CASE_ENUM_TO_STRING(PTI_CB_DOMAIN_DRIVER_MODULE_LOADED)
    PTI_CASE_ENUM_TO_STRING(PTI_CB_DOMAIN_DRIVER_MODULE_UNLOADED)
    PTI_CASE_ENUM_TO_STRING(PTI_CB_DOMAIN_INTERNAL_EVENT)
    PTI_CASE_ENUM_TO_STRING(PTI_CB_DOMAIN_INTERNAL_THREADS)
    PTI_CASE_ENUM_TO_STRING(PTI_CB_DOMAIN_INVALID)
    PTI_CASE_ENUM_TO_STRING(PTI_CB_DOMAIN_MAX)
  }

  return "INVALID";
}

const char* ptiCallbackPhaseTypeToString(pti_callback_phase phase) {
  switch (phase) {
    PTI_CASE_ENUM_TO_STRING(PTI_CB_PHASE_API_ENTER)
    PTI_CASE_ENUM_TO_STRING(PTI_CB_PHASE_API_EXIT)
    PTI_CASE_ENUM_TO_STRING(PTI_CB_PHASE_INTERNAL_THREAD_START)
    PTI_CASE_ENUM_TO_STRING(PTI_CB_PHASE_INTERNAL_THREAD_END)
    PTI_CASE_ENUM_TO_STRING(PTI_CB_PHASE_INTERNAL_EVENT)
    PTI_CASE_ENUM_TO_STRING(PTI_CB_PHASE_INVALID)
    PTI_CASE_ENUM_TO_STRING(PTI_CB_PHASE_MAX)
  }

  return "INVALID";
}

#undef PTI_CASE_ENUM_TO_STRING
