---

name: Linter Checks

on:
  push:
    branches: [ "master" ]
    paths:
      - sdk/**
  pull_request:
    branches: [ "master" ]
    paths:
      - sdk/**

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  run-format-check:

    container:
      image: ${{ vars.PTI_DOCKER_IMAGE }}

    if: vars.PTI_RUN_TESTS == 1

    runs-on: [self-hosted, Linux, pti]

    steps:
      - name: Clean
        run: rm -rf ./*

      - name: Checkout
        uses: actions/checkout@v4

      - name: Python Environment Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade setuptools wheel pip
          python -m pip install "clang-format>=18,<19" # Ubuntu 24.04 ships with clang-format 18

      - name: Check SDK Format
        working-directory: sdk
        run: |
          # Expedited configure
          cmake -S . -B build -DPTI_BUILD_TESTING=OFF -DPTI_BUILD_SAMPLES=OFF -DPTI_INSTALL=OFF
          cmake --build build --target format-chk
