---

name: Linter Checks

on:
  push:
    branches: [ "master" ]
    paths:
      - sdk/**
  pull_request:
    branches: [ "master" ]
    paths:
      - sdk/**

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  run-format-check:

    container:
      image: ${{ vars.PTI_DOCKER_IMAGE }}

    if: vars.PTI_RUN_TESTS == 1

    runs-on: [self-hosted, Linux, pti]

    steps:
      - name: Clean
        run: |
          rm -rf ./*
          rm -rf ./.venv
          rm -rf ./.cache

      - name: Checkout
        uses: actions/checkout@v4

      - name: Python Environment Setup
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.11'
          activate-environment: true
          cache-local-path: ${{ github.workspace }}/.cache/uv

      - name: Install Dependencies
        run: |
          uv pip install "clang-format>=18,<19"
          uv pip install ruff==0.15.15

      - name: Check SDK Format
        working-directory: sdk
        run: |
          # Expedited configure
          cmake -S . -B build -DPTI_BUILD_TESTING=OFF -DPTI_BUILD_SAMPLES=OFF -DPTI_INSTALL=OFF
          cmake --build build --target format-chk
